#pragma kernel CSMain
#include "Includes/Utils.compute"

RWTexture3D<float> OutputMap;
RWStructuredBuffer<uint> DensityMinMax;

[numthreads(8,8,8)]
void CSMain (int3 id : SV_DispatchThreadID)
{
    float minVal = asfloat(DensityMinMax[0]);
    float maxVal = asfloat(DensityMinMax[1]);

    float val = OutputMap[id];
    val = (val - minVal)/(maxVal - minVal);
    float normalizedDensity = clamp(val, 0.0, 1.0);
    //saturate(val); // opcional
    OutputMap[id] = normalizedDensity;
}